name: Triggered Pipeline

on:
  workflow_dispatch:
    inputs:
      inputData:
        description: "Data from the form"
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Echo input data
        run: echo "The input data is ${{ github.event.inputs.inputData }}"
